### ISSUE TITLE
Changing datagrid foreground color

### ISSUE THREAD

**Issue by Nunol** [firstfloorsoftware/mui#4]
Hello, 
is there a way to change row foreground color from codebehind?
the bellow code only seem to work if I remove this line from default assets. 
SolidColorBrush x:Key="DataGridCellForeground" Color="#333333" 

       
code: 
 private void dg_LoadingRow(object sender, DataGridRowEventArgs e)
{
                          e.Row.Foreground = Brushes.Red;
}

for 
e.Row.Background = Brushes.Red; it works correctly

**Comment by kozw** [comment]
DataGridCell Foreground always overrides DataRow Foreground. Setting the Background in code works, because the default DataGridCell.Background is set to transparent.

The best solution IMHO is to define a custom DataGridCell style derived from the default MUI style, where the DataGridCell.Foreground is bound to the DataRow.Foreground. Something like this works:

```xml
<Style TargetType="DataGridCell" BasedOn="{StaticResource {x:Type DataGridCell}}">
  <Setter Property="Foreground"
          Value="{Binding Foreground, RelativeSource={RelativeSource AncestorType=DataGridRow}}" />
</Style>
```

There are some gotchas when deriving from default MUI styles, explained in wiki article [Derive from MUI styles](https://github.com/firstfloorsoftware/mui/wiki/Derive-from-MUI-styles).

**Comment by Nunol** [comment]
thank you :)
