### ISSUE TITLE
Page Loaded event fires after unload

### ISSUE THREAD

**Issue by emGie007** [firstfloorsoftware/mui#60]
When navigating between pages, Loaded event on old page fires after Unloaded event. And then goes Loaded event on new page, and Unloaded event on old page again... The Loaded event while unloading old page is very disturbing for me. Is it error?

**Comment by kozw** [comment]
This behavior is by design. Happens because the ModernFrame uses a TransitioningContentControl which loads the previously content for animation purposes. Implement the IContent interface to handle OnNavigatedTo and From events instead of relying on OnLoad and OnUnload.

See also the [wiki](https://github.com/firstfloorsoftware/mui/wiki/Handle-navigation-events)
